### ISSUE TITLE
`gen_initramfs_list.sh` command line errors

### ISSUE THREAD

**Issue by Xylopyrographer** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#71]
Hi. Referencing MELP, 3rd ed, Chapter 5, _Creating a boot initramfs_, page 143.

The paragraph starting with "The task of creating an `initramfs` device table from scratch is made easier..." cites using the script located in `linux-stable/usr` and to change the `UID` and `GID` to `0` and `0`. However the command line example is in error and should read (if I understand correctly):

`$ bash linux-stable/usr/gen_initramfs_list.sh -u 0 -g 0 rootfs > initramfs-device-table`

And in the paragraph after, starting with "Using this script's `-o` option ..." it is unclear if the example command line should use the `-o` option? If so, the example command line should be modified how?

Thanks.

**Comment by fvasquez** [comment]
The book text and command match what Chris had for the 2nd Edition although I agree that the `1000` `UID` and `GID` don't appear to make sense here.

I think I added the information about the `-o` option. I should have provided an example of how to use it.

I will dig into the original script to confirm. It also looks like `gen_initramfs_list.sh` was renamed to `gen_initramfs.sh` back in 2020.

**Comment by fvasquez** [comment]
@Xylopyrographer `gen_initramf_list.sh` is supposed to change file UIDs and GIDs to `0`. This eliminates the need to run `sudo chown -R root:root *` inside the staging directory which can lead to problems down the road. The `-u 1000 -g 1000` tells the script to change files owned by UID and GID `1000` to UID and GID `0` (root). Unless you're on an Ubuntu system your UID and GID are likely not `1000`. For example:

```
❯ id -u frank
501
❯ id -g frank
20
```

So instead I would run:

```
❯ bash linux-stable/scripts/gen_initramfs_list.sh -u 501  -g 20 rootfs > initramfs.cpio
```

You only need `-o` option if you want to compress the generated cpio archive file. Otherwise, it's easier to just redirect output to a file like I did in the preceding command.

Here is the usage for `gen_initramfs_list.sh`:

```
Usage:
$0 [-o <file>] [-u <uid>] [-g <gid>] {-d | <cpio_source>} ...
	-o <file>      Create compressed initramfs file named <file> using
		       gen_init_cpio and compressor depending on the extension
	-u <uid>       User ID to map to user ID 0 (root).
		       <uid> is only meaningful if <cpio_source> is a
		       directory.  "squash" forces all files to uid 0.
	-g <gid>       Group ID to map to group ID 0 (root).
		       <gid> is only meaningful if <cpio_source> is a
		       directory.  "squash" forces all files to gid 0.
	<cpio_source>  File list or directory for cpio archive.
		       If <cpio_source> is a .cpio file it will be used
		       as direct input to initramfs.
	-d             Output the default cpio list.
```

The `gen_initramfs_list.sh` script dates back to 2006 and was renamed to `gen_initramfs.sh` because it is no longer meant to generate a device table.
